import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./OnboardingScreen/(components)/Header/Header";
import SideBar from "./(components)/SideBar/SideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Fairo Web App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} mmax-w-[1440px] h-[926px] md:h-[900px] bg-_bgColor`}
      >
        {children}
      </body>
    </html>
  );
}
