import localFont from "next/font/local";
import "./globals.css";

const myFont = localFont({
  src: "../public/fonts/Aeonik-Regular.ttf",
  display: "swap",
  weight: "400",
  variable: "--Aeonik",
});

export const metadata = {
  title: "Fairo Web App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${myFont.variable}`}>
      <body
        className={`max-w-[1440px] mx-auto h-[926px] md:h-[900px] bg-_bgSlateColor font-Aeonik`}
      >
        {children}
      </body>
    </html>
  );
}
